# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20170426_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(max_length=2)),
                ('hour', models.IntegerField(max_length=2)),
                ('project_id', models.IntegerField()),
                ('message_id', models.IntegerField()),
                ('visit', models.IntegerField(default=0)),
                ('trigger', models.IntegerField(default=0)),
                ('click', models.IntegerField(default=0)),
                ('close', models.IntegerField(default=0)),
                ('goal', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(max_length=2)),
                ('day', models.IntegerField(max_length=2)),
                ('project_id', models.IntegerField()),
                ('message_id', models.IntegerField()),
                ('visit', models.IntegerField(default=0)),
                ('trigger', models.IntegerField(default=0)),
                ('click', models.IntegerField(default=0)),
                ('close', models.IntegerField(default=0)),
                ('goal', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
