# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20170427_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayevent',
            name='day',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dayevent',
            name='hour',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='periodevent',
            name='day',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='periodevent',
            name='month',
            field=models.IntegerField(),
        ),
    ]
