# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20170427_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayevent',
            name='day',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='periodevent',
            name='month',
            field=models.IntegerField(default=0),
        ),
    ]
