# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20170427_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('message_id', models.IntegerField()),
                ('visit', models.IntegerField(default=0)),
                ('trigger', models.IntegerField(default=0)),
                ('click', models.IntegerField(default=0)),
                ('close', models.IntegerField(default=0)),
                ('goal', models.IntegerField(default=0)),
            ],
        ),
    ]
