# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_generalevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodevent',
            name='day',
            field=models.DateField(),
        ),
    ]
