# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20170428_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayevent',
            name='day',
            field=models.DateField(),
        ),
    ]
